on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: An integration test
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: |
        npm install -g @zeit/ncc
        npm install
        ncc build index.js
    - name: Run action
      id: action
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Assertion
      run: |
        if [[ "${{ steps.action.outputs.number }}" == "" ]]; then
          echo "PR not found"
          exit 1
        fi
        echo "${{ toJson(steps.action.outputs) }}"
  release:
    runs-on: ubuntu-latest
    name: Release new version
    needs: [test]
    steps:
      - name: Compile and commit
        run: |
          git add dist/index.js
          git commit -m 'Compile index.js'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
