on: [push]

jobs:
  integration_test:
    runs-on: ubuntu-latest
    name: An integration test
    steps:
    - name: Get PR info
      id: pr_info
      uses: kamatama41/set-pr-info-action@${{ github.sha }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get the outputs
      if: steps.pr_info.outputs.is_found
      run: |
        echo "The number of PR is ${{ steps.pr_info.outputs.number }}"
