on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: An integration test
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Generate index.js
      run: |
        npm i -g @zeit/ncc
        ncc build index.js
    - name: Run action
      id: action
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Assertion
      run: |
        if [[ "${{ steps.action.outputs.is_found }}" != "true" ]]; then
          echo "PR not found"
          exit 1
        fi
        echo "${{ toJson(steps.action.outputs) }}"
