on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: An integration test
    steps:
    - uses: actions/checkout@v2
    - name: Run action
      id: action
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Assertion
      run: |
        if [[ "${{ steps.action.outputs.is_found }}" != "true" ]]; then
          echo "PR not found"
          exit 1
        fi
        echo "${{ toJson(steps.action.outputs) }}"
